[package]
name = "taggr"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.13.0"
candid = "0.8"
canisters = { path = "../canisters" }
hex = "0.4"
ic-cdk = { version = "0.6.8", features = ["timers"] }
ic-cdk-macros = "0.6.8"
ic-certified-map = "0.3.2"
ic-ledger-types = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.6"
serde_cbor = "0.11"
serde_json = "1.0"
sha2 = "0.9.1"

[dev-dependencies]
actix-rt = "*"

[features]
dev = []
